# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa62808b26619178f928e64688697e7a5496bc40fed006138974e6fffa62153b8772c2aa3b7223d7ca9854c4320320e8f0901ab7d48b8018f5a48e4555d826d7

test:
  secret_key_base: 47d96bc9e01516a7652c4083c6d4d966e2d697d288d687031c2e95c241050e624c3aad11875a8bcaa68f203bce6ebcb70606a96d7feefc66aa8acbd85991f603

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
